# Generated by Django 6.0.2 on 2026-02-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hobbies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HobbyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "hobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="hobbies.hobby",
                    ),
                ),
            ],
            options={
                "db_table": "hobby_details",
                "ordering": ["-date_updated", "id"],
            },
        ),
    ]
