# Generated by Django 6.0.2 on 2026-02-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hobbies", "0002_hobbydetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hobbydetail",
            name="hobby",
            field=models.ForeignKey(
                db_column="parent_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="hobbies.hobby",
            ),
        ),
    ]
